# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Weather-Com
version:      0.5.3
version_from: 
installdirs:  site
requires:
    Data::Dumper:                  
    Locale::Maketext:              
    LWP::UserAgent:                
    Storable:                      
    Time::Format:                  1.0
    Time::Local:                   
    URI::Escape:                   
    XML::Simple:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
