--- #YAML:1.0
name:                Weather-Com
version:             0.5.5
abstract:            fetching weather information from I<weather.com>
license:             ~
author:              
    - Thomas Schnuecker <thomas@schnuecker.de>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Data::Dumper:                  
    Locale::Maketext:              
    LWP::UserAgent:                
    Storable:                      
    Time::Format:                  1.0
    Time::Local:                   
    URI::Escape:                   
    XML::Simple:                   
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
